skouat.ppde.donate:
    path: /donate
    defaults: { _controller: skouat.ppde.controller:handle }
skouat.ppde.ipn_listener:
    path: /ipn-listener
    defaults: { _controller: skouat.ppde.ipn_listener:handle }
