skouat_ppde_main_controller:
    path: /donate
    defaults: { _controller: skouat.ppde.controller:handle }
skouat_ppde_ipn_listener:
    path: /ipn-listener
    defaults: { _controller: skouat.ppde.ipn_listener:handle }
