imports:
    - { resource: tables.yml }

services:
    skouat.ppde.controller.admin.donation_pages:
        class: skouat\ppde\controller\admin_donation_pages_controller
        arguments:
            - @service_container
            - @skouat.ppde.operator
            - @request
            - @template
            - @user
            - %core.root_path%
            - %core.php_ext%

    skouat.ppde.controller.admin.overview:
        class: skouat\ppde\controller\admin_overview_controller
        arguments:
            - @auth
            - @cache
            - @config
            - @ext.manager
            - @log
            - @skouat.ppde.operator
            - @request
            - @template
            - @user
            - %core.root_path%
            - %core.php_ext%

    skouat.ppde.controller.admin.settings:
        class: skouat\ppde\controller\admin_settings_controller
        arguments:
            - @config
            - @service_container
            - @request
            - @template
            - @user

    skouat.ppde.entity.donation_pages:
        class: skouat\ppde\entity\donation_pages
        arguments:
            - @dbal.conn
            - @user
            - %skouat.ppde.tables.ppde_donation_pages%

    skouat.ppde.operator:
        class: skouat\ppde\operators\donation_pages
        arguments:
            - @service_container
            - @dbal.conn
            - %skouat.ppde.tables.ppde_donation_pages%
